name: Full Data Pipeline Scheduler

on:
  push:   # Runs on every code push
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST

jobs:
  run_data_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Country Fetcher
        run: python country_fetcher.py

      - name: Run DB to ADLS pipeline
        run: python db_to_adls_pipeline.py
